language: generic

dist: trusty

services:
  - docker

install:
  - docker pull lamtev/build-tools

script:
  - sudo chmod 755 travis_build.sh
  - docker run -v /home/travis/build/lamtev:/Go lamtev/build-tools /bin/bash -c "cd Go && ./travis_build.sh"
