language: generic

sudo: required

services:
- docker

before_install:
- docker pull lamtev/ubuntu-dev-tools

script:
  - sudo chmod 755 travis_build.sh
  - docker run -v /home/travis/build/vilegzhanina/Go:sources lamtev/ubuntu-dev-tools /bin/bash -c "cd /sources && ./travis_build.sh"
