language: generic

compiler: gcc

dist: trusty

sudo: required

cache:
  apt: true

matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test
    - env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
          sources: *sources


before_install:
  - lsb_release -a
  - sudo apt-add-repository -y ppa:beineri/opt-qt561-trusty
  - sudo apt-add-repository -y ppa:kojoley/boost
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y qt56base qt56declarative qt56translations
  - sudo apt-get install -y boost1.58
  - sudo apt-get install -y cmake
  - sudo apt-get install -y cloc
  - sudo apt-get install -y cppcheck
  - sudo apt-get install -y valgrind

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build .