language: cpp

compiler:
  - gcc
  
sudo: required

dist: trusty
  
before_install:
  - pwd
  - cmake --version
  - if [ -e "/etc/apt/sources.list.d/rabbitmq-source.list" ]; then sudo rm -f /etc/apt/sources.list.d/rabbitmq-source.list; fi
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qttools5-dev qttools5-dev-tools qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y cloc
  - export CXX=g++
  - export CC=gcc
  
install:
  #TODO install gcc 6.1
  - sudo apt-get install -qq g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50

script: 
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" ../sources/
  - cmake --build ./ --target GoTests --
  - make GoTests
  #- cd GoTests/UnitTests && ls && cd ../FunctionalTest && ls && cd ../..
  - cd GoTests/UnitTests && echo "Unit tests" && ./StoneTest && ./PointTest && ./BoardTest && ./MoveTest && ./GameProcessTest && cd ../FunctionalTest && echo "Functional test" && ./FTest && cd ../../../sources && echo "CLOC" && cloc GoEngine GoCUI GoGUI GoTests ./CMakeLists.txt
