language: generic

dist: trusty

services:
  - docker

install:
  - docker pull lamtev/cxx-build-tools

script:
  - docker run -v /home/travis/build/lamtev/Go:/Go lamtev/cxx-build-tools /bin/bash -c "cd Go && ./travis_build.sh"
